### ISSUE TITLE
idea: Horizontal Scrolling Suggestion

### ISSUE THREAD

**Issue by jfenton** [publicdomaincompany/scroll#10]
I love the. concept, but I find it works better if you flip it to infinitely horizontal scrolling. You can try it out just by adding e.g. via Chrome Inspector:

```
div.scrollPage {
   height: 85%;
 }
```

This would work great for Twitter Feeds, RSS etc.

**Comment by breck7** [comment]
Thanks for the code1 I was able to easily try it out:

https://user-images.githubusercontent.com/74692/108864193-0dae4100-7596-11eb-8a9f-387d384ee22c.mov

742 bonus points for providing a one liner. That is music to
my coding ears.

I do not like the current desktop reading experience. The
reading experience on the phone I really enjoy, with the
double tap to zoom in on an article. I want to have
something like that for desktop.

1. Horizontal scrolling I am personally not a fan of, having
spent a couple years working on a site that used
h-scrolling. It never grew on me.

2. That being said, there should be an easy way to override
any Scroll style. I think perhaps having a "scroll.hakon"
in a Scroll folder should be the way to do it. Then anyone
could more easily make desired style tweaks.

3. Still in the market for other ideas on how to improve
desktop reading experience, as it seems everyone is in
agreement that is sucks right now.

**Comment by breck7** [comment]
Actually, coming back to this one, I think your idea is perfect for the single article reading experience.

**Comment by breck7** [comment]
Added a single article reading experience, where a single article will flow into multiple columns. Example: https://breckyunits.com/how-james-park-built-fitbit.html

**Comment by telotortium** [comment]
On the desktop, this idea works a lot better if you override PageUp and PageDown to scroll left and right by screens. Here's how you implement that for https://breckyunits.com/how-james-park-built-fitbit.html (the site in the above comment):

```
document.onkeydown = function(e) {
    if (e.key === 'PageDown') {
        document.querySelector('html').scrollLeft += document.querySelector('div.scrollArticlePageComponent').clientWidth - 10
    }
    if (e.key === 'PageUp') {
        document.querySelector('html').scrollLeft -= document.querySelector('div.scrollArticlePageComponent').clientWidth - 10
    }
}
```
Also, the CSS should use `vh` (viewport height) as the length units to work correctly:

```
div.scrollArticlePageComponent {
   height: 85vh;
 }
```

**Comment by telotortium** [comment]
Couple of other ideas:

- Allow scrolling the article div:

   ```
   div.scrollArticlePageComponent {
       height: 85vh;
   }
   ```
   the `onkeydown` function can then be modified to replace `document.querySelector('html')` by `document.querySelector('div.scrollArticlePageComponent')`, which makes the headers and footers stationary.

- Set `tabindex="0"` on `div.scrollArticlePageComponent` so that the arrow keys work.
- Perhaps the up and down arrow keys should be captured to move the article left and right instead.

**Comment by martinetd** [comment]
Alternatively to horizontal scrolling, on desktop, paginate columns so that you get one screen worth -- e.g. something like reading in this order where one screen fits four "lines":
```
123
123
123
123
456
456
456
456
```
And have scroll somehow snap to column separations (like slides?)

the idea is the same anyway, having to go all the way back up from the bottom of the page when you're done with a column is pretty horrible when the column is long.

**Comment by telotortium** [comment]
@martinetd I wanted to do that, but I couldn't see any feature of CSS that would actually support that. The advantage of my kind of horizontal scrolling is that you can at least implement it with currently-supported features of CSS. You could envision your layout, but I think you would have to entirely depart from modeling your webpage as semantically-meaningful HTML and CSS - that would be the Google Docs approach (Google Docs is now moving from [HTML to Canvas-based rendering](https://workspaceupdates.googleblog.com/2021/05/Google-Docs-Canvas-Based-Rendering-Update.html) anyway).

**Comment by breck7** [comment]
> having to go all the way back up from the bottom of the page when you're done with a column is pretty horrible when the column is long.

Agreed! Room for improvement.

Fun to play with your demo telotortium. @martinetd I was thinking of that too, but couldn't figure it out without Javascript, which I'd like to avoid in the default theme. Perhaps a worthwhile strategy would be to have an advanced theme without the no Javascript constraint.

Another approach would be to research how this be done upstream at the browser level. I love @telotortium's Wikipedia example posted on HN (repasted below):

![image](https://user-images.githubusercontent.com/74692/141541360-3a7c9271-af3b-45b7-a2e6-874c0d834358.png)

A workaround for the status quo is that Scroll is designed with the assumption that the content is always public domain and readers should have 1 click access to the source for any publication, so should be easy to redisplay in the format of choice. Perhaps there are ways to expose more reading view options?

So to improve reading experience of long articles:

- have an advanced theme with Javascript and then compute best layouts for particular screen on the fly using CSS + JS
- wait for browsers/extensions to offer better column support upstream and then get that for free
- ideas for how to leverage the fact that all articles are public domain and source is always a step away?
