### ISSUE TITLE
🚀 make articles look nice on social media

### ISSUE THREAD

**Issue by breck7** [publicdomaincompany/scroll#31]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/publicdomaincompany/scroll/issues/31)

Bad:
<img width="610" alt="Screen Shot 2021-05-06 at 1 43 42 PM" src="https://user-images.githubusercontent.com/74692/117378426-17df9c00-ae71-11eb-8daf-afab9a8bdff4.png">

Good:
<img width="537" alt="Screen Shot 2021-05-06 at 1 45 03 PM" src="https://user-images.githubusercontent.com/74692/117378497-46f60d80-ae71-11eb-8229-5db74fc4a9b3.png">

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars.githubusercontent.com/u/74692?v=4' alt='breck7' width=24 height=24> breck7](https://issuehunt.io/u/breck7) ($50.00)

### Submitted pull Requests
- [#33 Update readme.scroll](https://issuehunt.io/r/publicdomaincompany/scroll/pull/33)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/publicdomaincompany/scroll/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by PatelRupen** [comment]
Tired:- Recently I have been given noodles on the topic of "advice" that the one I came here with is in front of me.
Wired:- This is the first house printed in 3D from raw earth
Multiple printers built the building in 200 hours using local soli, meaning it is zero-waste and no materials are needed to make it beautiful.

**Comment by breck7** [comment]
Basic version is live. https://github.com/publicdomaincompany/scroll/commit/67160ca51cc1920e470970c635b2a62be26884ac
