### ISSUE TITLE
Alternative language specifying syntax for "code" blocks 

### ISSUE THREAD

**Issue by ycd** [publicdomaincompany/scroll#6]
Currently dumbdown adds code block like this:

```md
code
     some code here
```

What would be an alternative to markdown's this syntax? 
```js
```js
```

In my opinion, using square brackets for adding classes, attributes looks great.

```md
code [js] 
    alert("alerted");
```

We can also extend this syntax for all sort of things

```
list [ordered]
 item Dumbdown supports lists
 item For now the keyword for an item is "item"
 item This is a very early version
 item Dumbdown is released to the public domain
 item If you want to make it better, please do!
```

**Comment by breck7** [comment]
I like it!

Let me just brain dump some alternatives:

```
code [js] 
    alert("alerted");
```

No brackets, using the 2nd cell as the language identifier:

```
code js
    alert("alerted");
```
Using a "Code" camel case suffix node:

```
jsCode
 alert("alerted");
cCode
 int main(void) {
  printf("hello, world\n");
 }
```

Similarly for lists. Anything ending in "List" could of of type
"listNode", so you could have: `orderedList`, `unorderedList`, et cetera.

**Comment by tomByrer** [comment]
1 or 2, but def NOT 3 please.

I would aim for descriptors that go general then specific, so any attributes should follow the inital flag.

**Comment by breck7** [comment]
3 seems strange, I agree, however
the suffix pattern is one that I've
found to be very ergonomic, when you have
support in your editor(s) for it.

**Comment by ycd** [comment]
Normally I would agree what @tomByrer have said, 3rd one looks horrible, but since this is dumbdown, i would go with it.

**Comment by ycd** [comment]
I have no idea what happened to dumbdown.

**Comment by breck7** [comment]
3 people argued it was a bad name.
I was convinced. Now called Scroll.
