### ISSUE TITLE
🐞 pages repeatedly reflow on load

### ISSUE THREAD

**Issue by breck7** [publicdomaincompany/scroll#8]
"The repeated reflowing on load is also rather obnoxious."

### Screen recording

https://user-images.githubusercontent.com/74692/108753206-848d0080-74e8-11eb-827c-93805f3c1f6e.mov

Reported by kyrias: https://lobste.rs/s/xyn2iy/scroll_new_way_publish#c_85jywz

Repro: visit https://breckyunits.com/

Is this a problem with CSS columns, or the youtube video includes, or img includes, or something else?

**Comment by breck7** [comment]
Helpful support from SO: https://stackoverflow.com/questions/66343672/why-is-page-using-css-columns-reflowing-on-load/66344455#66344455

The term we are looking for is how to avoid Layout Shifts.

**Comment by breck7** [comment]
![Screen Shot 2021-02-24 at 5 20 42 PM](https://user-images.githubusercontent.com/74692/109098038-a2af5800-76c4-11eb-9a21-4d8af215e140.png)

**Comment by mbarkhau** [comment]
I think the only way to avoid this would be to pre-compute the layout, so the browser has as little as possible to do once the page is loaded. The height for each text block would have to be known and to compensate for different text rendering on various platforms, there would probably have to be significant extra space available.

For this to work without javascript, there will probably have to be a few layouts pre-computed for various screen widths (one of which is selected via media queries).

**Comment by breck7** [comment]
Also have an anecdotal report that this is causing eInk browsers to crash. Perf may be an ongoing issue so perhaps putting some time into simple easy testing infra and instrumentation will be worth it.

**Comment by breck7** [comment]
perhaps we only show 3 pages of content at first, with a "view more" button to show all. maybe do it via query string  "index.html?viewAll=true"

**Comment by breck7** [comment]
Maybe we go with snippets and then you can click to view a whole article or click "show all" to view entire page.

**Comment by breck7** [comment]
This should be greatly reduced now.

 - Added lazy loading attribute to images
 - Scroll now looks up image size during build and injects that into HTML so browser can placehold room for images
 - I added help to the readme on how to programmatically use lighthouse to run perf report
 - Added skipIndexPage to make it easy to have a page not included in the index

On my site I:
 - I removed YouTube video on my site (now just click to go watch)
 - I removed unneeded javascript.
 - Reduced image sizes
